language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run test
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: rzMmhHyubl6HqqJxLcqkDGFxr11cf2K8bxNmjmxo6ycZuOS8MQQ1uMyUyG2fOq0heOYX36cb/JqLnn+L0SCDyJE0apXMt3oyAbdsiNCdbl5pIDGaS0Oi9tHm7FtzijtlBymGvgMpLW/NX6KfcQscgKyj7UHjDfRLAXY+1ekfuzRlijnYUtxHJlhBB3+102Z6MgGMNBrv46jE1k4WGJWIkKM5FwwFzSidP/wafPx/H1s96De0tezPhBr0rGnORBjN96aqlys3u+t2Ya6jnQXeJYIzLqz/LUYbNjEStBiBbbZcY0ifXwIGdcP2J1tkieJATbWYHITydkT1G/UhLBHh12R/9L8vml9OVz3EnVDeoSZb4cfW4R199IW3nBSbe+jvTlpQVDq2JLDOED/keaLBUNjzrzaXzatPfrNzZAlmzHZGWk2xlgN4m1nDi4GI0qsj1VqvRGKTZPmq+2KnkhBubzzIghC6aHsqFQq+quAvT0QDd1MUs4jMxOltqZfYqE2pLfmZuNh02zSiS5s1fdWe9IpbQgWlvzAV75ykJpuEmylMeUaN1iTWopkfoDLR1b9L2Jgcdn5xRcanFYUfm48Cs0TSe98YOdUCYW6L/5ToyyIA7yxyqvX8qmPjD4HUnmltPNTkLu6BYc/ijKgfawkI9gs08lQ6QJT7fXmZDRaQoJ8=
  on:
    branch: master
